### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by json1c** [json1c/telegram-raid-botnet#13]
# TODO

### Мелкие фиксы

- [x] Dict unpacking https://github.com/json1c/telegram-raid-botnet/blob/7b0978f6c697315f44ce9d0ac2f8599173d724f1/modules/types/account_settings.py#L19
- [ ] Нужно сделать нормальную типизацию в функциях

### Написать когда-нибудь

- [ ] Поддержку лангпаков
- [ ] Переписать модуль для первичной настройки, сделать процесс настройки более удобным
- [x] Поддержку прокси

### Крупные фиксы
- [ ] Переписать большинство старых модулей, исключить говнокод оттуда

**Comment by json1c** [comment]
- [ ] Убрать болт с ботнета

**Comment by NeynQ** [comment]
@json1c Болты это плохо

**Comment by Yaroslav1734** [comment]
@json1c А потом снова положить

**Comment by json1c** [comment]
@Yaroslav1734 Да

**Comment by Yaroslav1734** [comment]
@json1c Я так и знал

**Comment by fredkek** [comment]
add proxy

**Comment by json1c** [comment]
Dict unpacking +
Proxy +

**Comment by master88wi** [comment]
pls add mtproxy
